language: php
sudo: false
php:
  - hhvm
  - nightly
  - 7.0
  - 5.6
  - 5.5
  - 5.5.9

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit
