language: php
sudo: false
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3.3
  - 5.3
  - hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./phpunit
